USE codeup_test_db;
DROP TABLE IF EXISTS albums;
CREATE TABLE albums (
id INT unsigned NOT NULL AUTO_INCREMENT,
artist VARCHAR(30) NOT NULL,
name VARCHAR(100) NOT NULL,
release_date DATETIME NOT NULL,
sales FLOAT NOT NULL,
genre VARCHAR(500) NOT NULL,
PRIMARY KEY(id)
);